### ISSUE TITLE
tinc 1.0.25 doesn't stop on  Android 6.0.1

### ISSUE THREAD

**Issue by kjansik** [Vilbrekin/tinc_gui#36]
Tinc 1.0.25 doesn't stop on  Android 6.0.1 (Nexus 5, build MMB29Q). Log writes tincd terminated, but tinc continues, STOP button doesn't change, DEBUG button seems not working.
Tinc GUI can be forced to stop, but tincd is still running. 
Tinc config is identical with previous Lollipop. 
Let me know if any additional info needed

**Comment by tekoholic** [comment]
Same issue on Resurrection Remix v5.6.5 (Android 6.0.1) on a klteusc / SM-G900R4 / Galaxy S5

**Comment by chupanoid** [comment]
OS Android 6.0.1 (CM13)
Since the removal of daemon tincd, automate kill file 'tinc.pid'
Fix this problem:
public void stopTincd()
{
if (_started)
{
run("pkill tincd", null);
// int aPid = getPid();
// if (aPid != 0)
// {
// run("kill " + aPid + " || rm " + getFileStreamPath(PIDFILE), null);
// Log.d(Tools.TAG, "killed");
// }
}
_debug = false;
stopForeground(true);
// Do not call stopSelf(), in order to keep any unflushed logs until GUI activity is back
checkAndStopSelf();
// Ensure GUI is updated
call("tincd terminated.");
}
